import { readdir, readFile, writeFile, mkdir } from "node:fs/promises"
import { basename, dirname, join, relative } from "node:path"
import { fileURLToPath } from "node:url"
import { optimize } from "svgo"

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..")
const sourceRoot = join(packageRoot, "assets")
const generatedRoot = join(packageRoot, "src", "generated")

// Maps each assets/<folder> to the prefix used in generated logo names
// (e.g. assets/banks/color/ansar.svg -> bank-ansar).
const CATEGORY_PREFIXES = {
  "app-store": "app",
  automobiles: "automobile",
  banks: "bank",
  "business-chain-stores": "store",
  "detergent-hygiene": "detergent",
  "fashion-clothing": "fashion",
  "food-drink": "food",
  football: "football",
  "household-appliances": "appliance",
  "tech-companies": "tech",
  insurance: "insurance",
  isp: "isp",
  "media-news": "media",
  "organization-departments": "organization",
  "payment-gateways": "gateway",
  "social-media": "social",
  transportation: "transportation",
  tv: "tv",
  university: "university",
  vod: "vod",
  "website-applications": "website",
}

const kebab = (value) =>
  value
    .replace(/\.svg$/i, "")
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[^a-zA-Z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .toLowerCase()

const pascal = (value) =>
  value
    .split("-")
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join("")

async function walk(directory) {
  const entries = await readdir(directory, { withFileTypes: true })
  const files = await Promise.all(
    entries.map((entry) => {
      const path = join(directory, entry.name)
      return entry.isDirectory() ? walk(path) : path
    })
  )
  return files.flat().filter((path) => path.endsWith(".svg"))
}

function parseSvg(svg) {
  const viewBox = svg
    .match(/viewBox=["']([^"']+)["']/i)?.[1]
    ?.trim()
    .split(/[ ,]+/)
    .map(Number)
  if (!viewBox || viewBox.length !== 4 || viewBox.some(Number.isNaN))
    throw new Error("SVG is missing a valid viewBox")
  const body = svg
    .replace(/^[\s\S]*?<svg[^>]*>/i, "")
    .replace(/<\/svg>[\s\S]*$/i, "")
    .replace(/<!--([\s\S]*?)-->/g, "")
    .replace(/<(title|desc)>[\s\S]*?<\/\1>/gi, "")
    .replace(/\sdata-name=("[^"]*"|'[^']*')/gi, "")
    .replace(/\s+/g, " ")
    .replace(/> </g, "><")
    .trim()
  return {
    left: viewBox[0],
    top: viewBox[1],
    width: viewBox[2],
    height: viewBox[3],
    body,
  }
}

function optimizeSvg(svg) {
  return optimize(svg, {
    multipass: true,
    plugins: ["preset-default", "removeDimensions"],
  }).data
}

function makeMono(svg) {
  // currentColor lets consumers theme one monochrome source with CSS.
  return svg.replace(/fill=("|')(?!none\1)[^"']+\1/gi, 'fill="currentColor"')
}

const files = (await walk(sourceRoot)).sort()
const logos = { color: {}, mono: {} }
const records = []

for (const file of files) {
  const parts = relative(sourceRoot, file).split(/[\\/]/)
  const folder = parts[0]
  const category = CATEGORY_PREFIXES[folder]
  if (!category) throw new Error(`Unknown asset category folder: ${folder}`)
  const variant = parts[1].toLowerCase()
  const name = `${category}-${kebab(basename(file))}`
  let source = await readFile(file, "utf8")

  if (name === "gateway-sep") {
    // SEP's source contains a presentation-only white canvas around the artwork.
    source = source
      .replace(/<path\b[\s\S]*?\/>/i, "")
      .replace(/viewBox=("|')0 0 710 356\1/i, 'viewBox="60 60 591 239"')
  }

  const svg = optimizeSvg(variant === "mono" ? makeMono(source) : source)
  const icon = parseSvg(svg)
  logos[variant][name] = icon
  records.push({
    name,
    title:
      name === "gateway-sep"
        ? "SEP"
        : basename(file, ".svg").replaceAll("-", " "),
    category,
    variant,
    icon,
  })
}

const CATEGORY_PREFIX_PATTERN = Object.values(CATEGORY_PREFIXES).join("|")
const LOGO_NAME_RE = new RegExp(
  `^(?:${CATEGORY_PREFIX_PATTERN})-[a-z0-9]+(?:-[a-z0-9]+)*$`
)

function validateRecords(items) {
  const seen = new Set()
  for (const { name, variant, icon } of items) {
    const key = `${variant}:${name}`
    if (seen.has(key)) throw new Error(`Duplicate logo: ${key}`)
    if (!LOGO_NAME_RE.test(name)) throw new Error(`Invalid logo name: ${name}`)
    if (!icon.body) throw new Error(`Logo has no SVG body: ${key}`)
    seen.add(key)
  }
}

validateRecords(records)

await mkdir(generatedRoot, { recursive: true })

const names = [...new Set(records.map(({ name }) => name))].sort()
const dataSource = `// Generated by scripts/generate.mjs. Do not edit.\nimport type { LogoIconData } from "../types.js"\n\nexport const logoNames = ${JSON.stringify(names)} as const\nexport type LogoName = (typeof logoNames)[number]\nexport type LogoVariant = "color" | "mono"\n\nexport const colorLogos: Record<LogoName, LogoIconData> = ${JSON.stringify(logos.color, null, 2)}\nexport const monoLogos: Record<LogoName, LogoIconData> = ${JSON.stringify(logos.mono, null, 2)}\n`
await writeFile(join(generatedRoot, "data.ts"), dataSource)

const reactSource = `// Generated by scripts/generate.mjs. Do not edit.\nimport { LogoIcon, type LogoProps } from "../react.js"\n\n${records
  .map(({ name, variant, icon }) => {
    const component = `${pascal(name)}${variant === "color" ? "Color" : "Mono"}`
    return `export function ${component}(props: LogoProps) { return <LogoIcon icon={${JSON.stringify(icon)}} {...props} /> }`
  })
  .join("\n")}\n`
await writeFile(join(generatedRoot, "react-icons.tsx"), reactSource)

const vueSource = `// Generated by scripts/generate.mjs. Do not edit.\nimport { defineComponent, h } from "vue"\nimport { LogoIcon } from "../vue.js"\n\n${records
  .map(({ name, variant, icon }) => {
    const component = `${pascal(name)}${variant === "color" ? "Color" : "Mono"}`
    return `export const ${component} = defineComponent({ name: "${component}", inheritAttrs: false, setup(_, { attrs }) { return () => h(LogoIcon, { ...attrs, icon: ${JSON.stringify(icon)} }) } })`
  })
  .join("\n")}\n`
await writeFile(join(generatedRoot, "vue-icons.ts"), vueSource)

// Per-category chunks let consumers (like the docs site) dynamically import
// only the logo data they actually need instead of the entire dataset.
const categoriesDir = join(generatedRoot, "categories")
await mkdir(categoriesDir, { recursive: true })

const byCategory = new Map()
for (const { name, category, variant, icon } of records) {
  if (!byCategory.has(category))
    byCategory.set(category, { color: {}, mono: {} })
  byCategory.get(category)[variant][name] = icon
}

for (const [category, group] of byCategory) {
  const categorySource = `// Generated by scripts/generate.mjs. Do not edit.\nimport type { LogoIconData } from "../../types.js"\n\nexport const colorLogos: Record<string, LogoIconData> = ${JSON.stringify(group.color, null, 2)}\nexport const monoLogos: Record<string, LogoIconData> = ${JSON.stringify(group.mono, null, 2)}\n`
  await writeFile(join(categoriesDir, `${category}.ts`), categorySource)
}

const categoryKeys = [...byCategory.keys()].sort()
const categoriesIndexSource = `// Generated by scripts/generate.mjs. Do not edit.\nimport type { LogoIconData } from "../../types.js"\n\ntype CategoryModule = {\n  colorLogos: Record<string, LogoIconData>\n  monoLogos: Record<string, LogoIconData>\n}\n\nexport const categoryLoaders: Record<string, () => Promise<CategoryModule>> = {\n${categoryKeys
  .map((category) => `  ${JSON.stringify(category)}: () => import("./${category}.js"),`)
  .join("\n")}\n}\n`
await writeFile(join(categoriesDir, "index.ts"), categoriesIndexSource)
